# Melody Manager Configuration
melody:
  version: 1.0.0
  author: baizeyv
  link: "https://else.wiki"
  docPath: "/doc"

# Mybatis Plus Configuration
mybatis-plus:
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:*:mybatis/**/*Mapper.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/melody
    username: root
    password: fahaxiki

server:
  port: 7373